spring.application.name=chatweb
api.security.token.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/chatweb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect